version: '3'

services:
  backend:
    build: ./TodoApp/backend
    command: sh -c "uvicorn books:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app



# version: '3.8'

# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"

#   backend:
#     build: ./backend
#     ports:
#       - "80:80"
#     depends_on:
#       - postgresql
#       - jwt
#     environment:
#       DATABASE_URL: postgresql://myuser:mypassword@postgresql:5432/mydatabase
#       SECRET_KEY: mysecretkeyforjwt

#   database:
#     build: ./postgresql
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#       POSTGRES_DB: mydatabase

#   jwt:
#     build: ./jwt
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgresql
#     environment:
#       DATABASE_URL: postgresql://myuser:mypassword@postgresql:5432/mydatabase
#       SECRET_KEY: mysecretkeyforjwt
