# Wybierz obraz bazowy
FROM postgres:latest

# Ustaw zmienne środowiskowe
ENV POSTGRES_USER=myuser \
    POSTGRES_PASSWORD=mypassword \
    POSTGRES_DB=mydatabase

# Otwórz port, na którym będzie działać serwer
EXPOSE 5432