



# # Wybierz obraz bazowy
# FROM node:14-alpine

# # Ustaw katalog roboczy
# WORKDIR /app

# # Skopiuj pliki aplikacji do kontenera
# COPY ./app /app

# # Zainstaluj zależności
# RUN npm install

# # Uruchom aplikację
# CMD ["npm", "start"]