




# # Wybierz obraz bazowy
# FROM python:3.9-slim

# # Ustaw katalog roboczy
# WORKDIR /app

# # Skopiuj pliki aplikacji do kontenera
# COPY ./app /app

# # Zainstaluj zależności
# RUN pip install --upgrade pip && \
#     pip install fastapi uvicorn[standard] python-dotenv PyJWT psycopg2-binary SQLAlchemy

# # Otwórz port, na którym będzie działać serwer
# EXPOSE 8000

# # Uruchom serwer FastAPI
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
